python refine.py \
--base_dir /data/chesapeake_bay_lulc/outputs/preprocessed \
--epsg epsg-32618 \
--dataset clinton \
--resolution 1.0 \
--unary_src dynamicworld \
--feature_set naip naip-nir naip-ndvi dsm surface_height \
--theta_alpha 195 \
--theta_beta_list 9 9 9 9 9 9 9 \
--theta_gamma 1 \
--w1 10 \
--w2 1 
