python refine.py \
--base_dir /media/hdd2/data/chesapeake_bay_lulc/outputs/preprocessed \
--epsg epsg-32618 \
--dataset virginia_beach_creeds \
--resolution 1.0 \
--unary_src dynamicworld \
--feature_set naip \
--theta_alpha 195 \
--theta_beta 7 \
--theta_gamma 200 \
--w1 1 \
--w2 1 \
--output_dir inference_outputs/nll_unconstrained
